"""add new column datetime to game ver

Revision ID: 02aab20a3247
Revises: 107766b892a5
Create Date: 2018-10-14 16:52:21.362260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aab20a3247'
down_revision = '107766b892a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_ver_game', sa.Column('timestamp', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results_ver_game', 'timestamp')
    # ### end Alembic commands ###
