"""task table

Revision ID: 1c20d2a4c4c2
Revises: fee499454f1c
Create Date: 2018-09-16 19:17:56.309974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c20d2a4c4c2'
down_revision = 'fee499454f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('Mp3url', sa.Text(), nullable=False))
    op.add_column('results', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('results', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('answer', sa.TEXT(), nullable=False))
    op.drop_column('results', 'text')
    op.drop_column('results', 'Mp3url')
    # ### end Alembic commands ###
