"""empty message

Revision ID: 6788daa1f979
Revises: 5de9d4af8a4f
Create Date: 2018-10-17 15:45:30.317295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6788daa1f979'
down_revision = '5de9d4af8a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_ver_easy', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('results_ver_easy', sa.Column('datetime', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results_ver_easy', 'datetime')
    op.drop_column('results_ver_easy', 'category')
    # ### end Alembic commands ###
