"""add new column category to game ver

Revision ID: 8d5f3baea622
Revises: 046aa2f36abf
Create Date: 2018-10-15 10:02:33.966133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5f3baea622'
down_revision = '046aa2f36abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_ver_game', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results_ver_game', 'category')
    # ### end Alembic commands ###
