"""empty message

Revision ID: 900ef7f87e6d
Revises: a81d8b2ffc41
Create Date: 2018-09-25 20:02:50.806806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900ef7f87e6d'
down_revision = 'a81d8b2ffc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_ver_game', sa.Column('answerTime', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results_ver_game', 'answerTime')
    # ### end Alembic commands ###
